project: Test project
task: push
seed: 0
width: 96
height: 96
n_envs: 24
learning_rate: 3e-4
n_steps: 512
batch_size: 256
n_epochs: 20
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
clip_range_vf: null
normalize_advantage: True
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
use_sde: False
sde_sample_freq: -1
target_kl: null
policy_kwargs: null
verbose: 2
device: auto
n_eval_episodes: 20
total_timesteps: 100000000
eval_freq: 750
timelimit: null

#project: Test project
#task: push
#seed: 0
#width: 96
#height: 96
#n_envs: 1
#learning_rate: 3e-4
#n_steps: 128
#batch_size: 64
#n_epochs: 8
#gamma: 0.99
#gae_lambda: 0.95
#clip_range: 0.2
#clip_range_vf: null
#normalize_advantage: True
#ent_coef: 0.01
#vf_coef: 0.5
#max_grad_norm: 0.5
#use_sde: False
#sde_sample_freq: -1
#target_kl: null
#policy_kwargs: null
#verbose: 2
#device: auto
#n_eval_episodes: 2
#total_timesteps: 100000000
#eval_freq: 50
#timelimit: 50